// packages/l1_interference/lib/src/gop_scorer.dart
//
// Goodness of Pronunciation (GOP) Scoring Engine.
//
// Computes per-phoneme log-posterior ratios over CTC acoustic frame posteriors
// generated by the ONNX Runtime IndicConformer model.

import 'dart:math' as math;
import 'package:meta/meta.dart';

/// Single scored phoneme segment.
@immutable
class PhonemeScore {
  final String phonemeIpa;
  final int startFrame;
  final int endFrame;
  final double gopScore;
  final double confidence;
  final bool isPass;

  const PhonemeScore({
    required this.phonemeIpa,
    required this.startFrame,
    required this.endFrame,
    required this.gopScore,
    required this.confidence,
    required this.isPass,
  });
}

/// Aggregated assessment for a spoken utterance.
@immutable
class GOPAssessment {
  final String targetText;
  final List<String> targetPhonemes;
  final double overallScore; // 0.0 - 100.0
  final List<PhonemeScore> phonemeScores;
  final List<String> weakPhonemes;

  const GOPAssessment({
    required this.targetText,
    required this.targetPhonemes,
    required this.overallScore,
    required this.phonemeScores,
    required this.weakPhonemes,
  });
}

/// GOP Scorer calculating log posterior ratios.
class DartGOPScorer {
  final double gopThreshold;

  const DartGOPScorer({this.gopThreshold = -2.5});

  /// Computes GOP scores given a 2D matrix of log probabilities [time_steps, vocab_size]
  /// and target phoneme sequence.
  GOPAssessment scoreUtterance({
    required List<List<double>> ctcLogProbs,
    required Map<String, int> vocabMap,
    required List<String> targetPhonemes,
    String targetText = '',
  }) {
    final int t = ctcLogProbs.length;
    final int n = targetPhonemes.length;

    if (t == 0 || n == 0) {
      return GOPAssessment(
        targetText: targetText,
        targetPhonemes: targetPhonemes,
        overallScore: 0.0,
        phonemeScores: const [],
        weakPhonemes: const [],
      );
    }

    final int framesPerPhoneme = math.max(1, t ~/ n);
    final List<PhonemeScore> scores = [];
    final List<double> gopValues = [];

    for (int i = 0; i < n; i++) {
      final String ph = targetPhonemes[i];
      final int startF = i * framesPerPhoneme;
      final int endF = (i == n - 1)
          ? t - 1
          : math.min(t - 1, (i + 1) * framesPerPhoneme - 1);

      final int? tokenId = vocabMap[ph];
      double gopVal = -1.0;

      if (tokenId != null && startF <= endF) {
        final List<double> frameScores = [];
        for (int frame = startF; frame <= endF; frame++) {
          final List<double> row = ctcLogProbs[frame];
          final double targetLogP = row[tokenId];

          // Compute max competing log prob
          double maxCompeting = -double.infinity;
          for (int v = 0; v < row.length; v++) {
            if (v != tokenId && row[v] > maxCompeting) {
              maxCompeting = row[v];
            }
          }
          frameScores.add(targetLogP - maxCompeting);
        }

        if (frameScores.isNotEmpty) {
          gopVal = frameScores.reduce((a, b) => a + b) / frameScores.length;
        }
      }

      gopValues.add(gopVal);
      final bool pass = gopVal >= gopThreshold;
      final double conf = math.exp(math.min(0.0, gopVal));

      scores.add(PhonemeScore(
        phonemeIpa: ph,
        startFrame: startF,
        endFrame: endF,
        gopScore: gopVal,
        confidence: conf,
        isPass: pass,
      ));
    }

    final double meanGop = gopValues.isEmpty
        ? -10.0
        : gopValues.reduce((a, b) => a + b) / gopValues.length;

    // Normalization to 0-100 scale
    final double overall = 100.0 / (1.0 + math.exp(-0.8 * (meanGop + 1.5)));

    final List<String> weak = scores
        .where((s) => !s.isPass)
        .map((s) => s.phonemeIpa)
        .toSet()
        .toList();

    return GOPAssessment(
      targetText: targetText,
      targetPhonemes: targetPhonemes,
      overallScore: double.parse(overall.toStringAsFixed(1)),
      phonemeScores: scores,
      weakPhonemes: weak,
    );
  }
}
